export const actionKeys = {
  START_FETCHING: "START_FETCHING",
  END_FETCHING: "END_FETCHING",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
  SET_COUNT: "SET_COUNT",
};